### ISSUE TITLE
complete pageに関する質問

### ISSUE THREAD

**Issue by kogaokumura** [shinonome-inc/kogaokumura-frontend-basic-last-assignment#18]
PRを出してページを完成させるに書いてある手順通り行ったのですが、画像が反映されていません。chromeでindex.htmlを開くと画像が表示されます。
imgまでのパスは../../../imgと../imgの2つは試してみたのですが、できませんでした。
なぜ画像が反映されないのか教えていただきたいです。

https://github.com/shinonome-inc/kogaokumura-frontend-basic-last-assignment/pull/17

**Comment by minezaki-mutsuki** [comment]
https://playground.wraptas.site/c8be28950297483ba8525455c2b3a80c

リポジトリの欠陥かと思われます、一旦こちら試してみてください！
